"""Pydantic contracts for Agent-Analyst FinOps results."""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from enum import StrEnum

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, computed_field, field_validator

from cloud_finops_agent.models.aws_resources import AWSResourceType


class FindingSeverity(StrEnum):
    """Business impact level for a FinOps finding."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class FindingType(StrEnum):
    """Supported optimization issue categories."""

    IDLE_RESOURCE = "idle_resource"
    OVERPROVISIONED_RESOURCE = "overprovisioned_resource"
    UNUSED_STORAGE = "unused_storage"
    MISSING_LIFECYCLE_POLICY = "missing_lifecycle_policy"
    UNOPTIMIZED_STORAGE_CLASS = "unoptimized_storage_class"
    ANOMALOUS_METRIC_PATTERN = "anomalous_metric_pattern"
    GOVERNANCE_RISK = "governance_risk"


class KnowledgeBaseRuleReference(BaseModel):
    """Reference to the RAG knowledge-base rule used to justify a finding."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    rule_id: str = Field(min_length=1, description="Stable rule identifier from Qdrant payload.")
    title: str = Field(min_length=1, description="Human-readable rule title.")
    source: str = Field(
        default="AWS Well-Architected Framework",
        min_length=1,
        description="Source document or framework name.",
    )
    source_url: str | None = Field(default=None, description="Optional source URL.")
    qdrant_point_id: str | None = Field(default=None, description="Qdrant point id used for traceability.")
    relevance_score: float | None = Field(default=None, ge=0, le=1)


class FinOpsFinding(BaseModel):
    """Single FinOps anomaly or optimization opportunity produced by Agent-Analyst."""

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    finding_id: str = Field(
        validation_alias=AliasChoices("finding_id", "id"),
        min_length=1,
        description="Stable finding identifier generated by the analyst.",
    )
    resource_id: str = Field(min_length=1, description="AWS resource id associated with the finding.")
    resource_type: AWSResourceType = Field(description="AWS resource type associated with the finding.")
    finding_type: FindingType = Field(description="Optimization issue category.")
    severity: FindingSeverity = Field(default=FindingSeverity.MEDIUM)
    current_monthly_cost: Decimal = Field(
        validation_alias=AliasChoices("current_monthly_cost", "current_cost"),
        ge=Decimal("0"),
        description="Current estimated monthly cost in USD.",
    )
    potential_monthly_savings: Decimal = Field(
        validation_alias=AliasChoices("potential_monthly_savings", "potential_savings"),
        ge=Decimal("0"),
        description="Estimated monthly savings in USD.",
    )
    confidence_score: float = Field(
        default=0.75,
        ge=0,
        le=1,
        description="Analyst confidence in the finding and recommendation.",
    )
    rationale: str = Field(
        min_length=20,
        description="Concise reasoning explaining why this resource is an optimization candidate.",
    )
    recommendation: str = Field(
        min_length=10,
        description="Recommended remediation action for Agent-Executor.",
    )
    rule_reference: KnowledgeBaseRuleReference = Field(
        description="Knowledge-base rule that supports this finding.",
    )

    @field_validator("finding_type", mode="before")
    @classmethod
    def normalize_finding_type(cls, value: object) -> object:
        """Normalize LLM-style finding type strings into enum-compatible values."""

        if isinstance(value, str):
            normalized = value.strip().lower().replace(" ", "_").replace("-", "_")
            if normalized == "over_provisioned_resource":
                return FindingType.OVERPROVISIONED_RESOURCE
            return normalized
        return value

    @field_validator("potential_monthly_savings")
    @classmethod
    def quantize_savings(cls, value: Decimal) -> Decimal:
        """Normalize savings precision for deterministic reports and tests."""

        return value.quantize(Decimal("0.0001"))

    @field_validator("current_monthly_cost")
    @classmethod
    def quantize_current_cost(cls, value: Decimal) -> Decimal:
        """Normalize cost precision for deterministic reports and tests."""

        return value.quantize(Decimal("0.0001"))


class OptimizationPlan(BaseModel):
    """Aggregated optimization plan created from Analyst findings."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    plan_id: str = Field(min_length=1, description="Stable identifier for this optimization plan.")
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    findings: list[FinOpsFinding] = Field(default_factory=list)
    summary: str = Field(
        default="No optimization findings were detected.",
        min_length=1,
        description="Executive summary suitable for the final Markdown report.",
    )

    @computed_field
    @property
    def total_potential_monthly_savings(self) -> Decimal:
        """Return aggregated monthly savings across all findings."""

        total = sum((finding.potential_monthly_savings for finding in self.findings), Decimal("0"))
        return total.quantize(Decimal("0.0001"))

    @computed_field
    @property
    def finding_count(self) -> int:
        """Return the number of optimization findings."""

        return len(self.findings)

    @field_validator("generated_at")
    @classmethod
    def ensure_utc_generated_at(cls, value: datetime) -> datetime:
        """Normalize plan generation timestamp to UTC."""

        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)
